# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Isha_ABI'
    subscriptionId: 'cebb7b05-9e26-4fa4-a9e6-7cd948b9b6ca'
    action: 'Create Or Update Resource Group'
    resourceGroupName: $(Test_RG)
    templateLocation: 'Linked artifact'
    csmFile: '$(Pipeline.Workspace)/databricks/iac/databricks.json'
    deploymentMode: 'Incremental'


